"use strict";


const palabras4Letras = [
    "para", "vida", "amor", "cosa", "duda", "poco", "nino", "hijo", "alto", "tema",
    "idea", "olor", "pero", "guia", "dano", "fiel", "duro", "ropa", "pues", "beso",
    "util", "base", "caer", "alma", "casa", "raro", "bebe", "frio", "show", "real",
    "caso", "sino", "otro", "haya", "area", "paso", "oler", "bajo", "como", "azul",
    "tipo", "peso", "moda", "agua", "fase", "suma", "mapa", "sano", "item", "huir",
    "malo", "raza", "usar", "amar", "leer", "onda", "rojo", "obra", "fino", "meta",
    "bien", "cima", "odio", "auge", "todo", "cama", "vago", "rico", "piel", "ruta",
    "reir", "afan", "unir", "mesa", "algo", "ijar", "cara", "esta", "zona", "musa",
    "dama", "rudo", "ente", "isla", "leal", "modo", "azar", "debe", "acto", "casi",
    "caro", "yoga", "yapa", "este", "plan", "sexo", "arte", "agil", "cada", "loco",
    "ocio", "ojos", "gato", "alba", "solo", "papa", "rifa", "apto", "mano", "olla",
    "nota", "boda", "baul", "esto", "auto", "giro", "reto", "vivo", "masa", "cura",
    "pais", "dona", "nada", "foto", "gozo", "rulo", "club", "roto", "dado", "atar",
    "tono", "aqui", "aire", "hora", "pena", "tubo", "jefe", "eden", "boca", "yate",
    "oido", "lujo", "raiz", "vela", "fama", "puro", "seco", "edad", "vano", "asco",
    "capa", "flor", "dato", "asno", "dios", "pago", "lote", "lado", "risa", "muro",
    "humo", "pene", "pelo", "rayo", "toma", "rama", "arco", "hada", "miel", "juez",
    "luna", "caos", "cita", "mira", "mono", "joya", "voto", "robo", "reja", "nudo", 
    "nulo", "caja", "hito", "fila", "foco", "lazo", "orar", "hilo", "ayer", "pico",
    "menu", "urna", "gama", "arar", "vino", "nexo", "piso", "alta", "baja", "nido",
    "bano", "wifi", "aula", "cola", "hoja", "tapa", "hoyo", "peor", "nube", "pose", 
    "arma", "celo", "dedo", "rosa", "roca", "puta", "cono", "irse", "palo", "cabo",   
    "afin", "seno", "alli", "fijo", "tino", "moto", "tasa", "nave", "liso", "oral",
    "yoyo", "gana", "laso", "cena", "oleo", "leve", "bobo", "guru", "roer", "gula",
    "cafe", "rabo", "bote", "tela", "mero", "foca", "nato", "ante", "trio", "lodo", 
    "zaga", "cruz", "culo", "sexy", "aseo", "alza", "vaso", "lava", "bota", "dote", 
    "lago", "cepa", "copa", "coro", "orbe", "aura", "pasa", "acta", "goma", "caca", 
    "diva", "cria", "yeso", "tope", "mito", "caza", "mudo", "sala", "cayo", "juan", 
    "izar", "velo", "mina", "fuga", "sede", "gris", "viga", "soga", "kiwi", "maiz",
    "dolo", "rima", "rana", "rizo", "ateo", "pila", "zoom", "mago", "mimo", "cavo",
    "alla", "veto", "kilo", "lema", "pedo", "jugo", "cojo", "ovni", "loma", "timo",
    "vena", "mono", "zumo", "gala", "lana", "faro", "vara", "liga", "test", "liar",
    "mona", "acre", "taza", "lomo", "buho", "ogro", "veda", "ceno", "faja", "paga",
    "gota", "raya", "codo", "mate", "sito", "clan", "paja", "proa", "tomo", "teta",
    "pato", "iris", "pase", "tren", "zote", "tiro", "tala", "plus", "ergo", "pozo", 
    "sana", "riel", "tira", "coco", "muda", "filo", "ramo", "moho", "bata", "ubre",
    "grua", "mula", "luto", "lata", "moza", "vale", "mama", "pote", "papa", "foro",
    "vaya", "saga", "jeta", "daga", "mica", "cuna", "cebo", "nuca", "pomo", "poso",
    "tajo", "saca", "dejo", "pito", "cero", "bala", "taco", "cana", "veta", "sima", 
    "buen", "aval", "hola", "moro", "coca", "mozo", "domo", "calo", "tras", "foso", 
    "duna", "albo", "sien", "cien", "data", "dura", "baba", "saco", "mazo", "cala", 
    "sumo", "toro", "tara", "sebo", "teja", "vate", "coma", "bola", "laxo", "pesa", 
    "ocre", "aspa", "zeta", "gran", "pica", "lego", "opio", "copo", "orca", "area", 
    "sexo", "vega", "cabe", "maza", "miga", "raid", "poda", "nata", "cava", "gaga", 
    "dije", "cazo", "hipo", "polo", "oval", "azul", "slip", "pijo", "boya", "higo", 
    "soto", "atun", "tina", "cuba", "pisa", "pino", "dejo", "mulo", "fosa", "nasa", 
    "sexi", "losa", "gajo", "leva", "cree", "vive", "fina", "maja", "silo", "goce", 
    "neto", "tres", "paro", "limo", "cese", "doma", "baya", "roce", "mote", "sube", 
    "pata", "cubo", "cata", "fiar", "nodo", "arca", "mata", "cota", "lelo", "rota", 
    "fosa", "pega", "mole", "crio", "orin", "peon", "majo", "abra", "romo", "alud", 
    "bono", "rezo", "raso", "misa", "deje", "gema", "nene", "orto", "film", "gato",
    "buzo", "mora", "diga", "agro", "capo", "seso", "puto", "mear", "tele", "caja", 
    "cupo", "asar", "tiza", "roer", "gira", "nana", "bufo", "cata", "cepo", "tabu", 
    "feto", "nerd", "orco", "leve", "lila", "ojal", "bici", "pita", "acre", "sofa", 
    "alce", "miel", "lona", "alar", "tufo", "mota", "rubi", "pana", "boto", "cale", 
    "sopa", "lupa", "riso", "fajo", "unto", "hoya", "sapo", "diva", "pava", "lapo", 
    "pibe", "loza", "cuco", "pera", "peca", "maga", "gasa", "soda", "riel", "coso",
    "seca", "muta", "loba", "topa", "puja", "pepa", "peca", "adan", "faca", "piba",
    "napa", "deba", "pipa", "jaez", "acne", "pena", "cito", "puso", "deci", "usan",    
    "vaca", "arpa", "eras", "pide", "olio", "goza", "crea", "arpo", "suda", "pido",
    "creo", "deja", "siga", "sudo", "teme", "iras", "leia", "dice", "robe", "alzo", 
    "rote", "cien", "mala", "temo", "mide", "poca", "digo", "veni", "sera", "mido",
    "boba", "nula", "coja", "echa", "anda", "pedi", "debo", "echo", "popa", "dijo",
    "pego", "sean", "cose", "medi", "seas", "puna", "crei", "dira", "hija", "vivi", 
    "alfa", "debi", "rime", "dire", "lean", "eche", "rige", "pida", "erra", "leas", 
    "rige", "sale", "muto", "rica", "mida", "bebo", "vias", "pone", "mete", "lavo", 
    "ligo", "eres", "topo", "meto", "hace", "subo", "leed", "tome", "roja", "hago", 
    "gano", "abre", "sali", "apta", "roma", "abro"   
  ];
  const totalPalabras4letras = palabras4Letras.length;

  const palabras5Letras = [
    "capaz", "venta", "cielo", "ojala", "haber", "traer", "pluma", "abrir", "viejo", "matar",
    "banal", "local", "icono", "flaco", "oveja", "epoca", "labor", "rumbo", "globo", "total",
    "grito", "spray", "ebano", "firme", "denso", "pobre", "copia", "senor", "estar", "igual",
    "mania", "osado", "vivir", "gordo", "senda", "chico", "futil", "ciego", "vasto", "clase",
    "temor", "parar", "pagar", "creer", "serio", "veloz", "lejos", "mismo", "honor", "optar",
    "etica", "sobre", "basar", "morir", "razon", "medio", "audaz", "jamas", "ufano", "error",
    "color", "motor", "curar", "joven", "ocaso", "parco", "dieta", "suelo", "justo", "corte",
    "plano", "burdo", "ganar", "echar", "grave", "grato", "broma", "gente", "pieza", "acido",
    "sucio", "visto", "ajeno", "gozar", "texto", "culto", "donar", "furor", "queja", "corto",
    "clave", "durar", "sueno", "usted", "brisa", "valla", "hogar", "fondo", "obvio", "gusto",
    "bello", "meter", "nacer", "cauto", "listo", "sello", "medir", "mover", "guapa", "hasta",
    "arido", "fluir", "rueda", "pausa", "lecho", "tonto", "celos", "legal", "casta", "aroma",
    "stock", "pegar", "punta", "dicho", "cinta", "pasto", "beber", "ciclo", "regar", "padre",
    "turno", "noche", "playa", "danza", "calor", "juego", "andar", "logro", "lucha", "bingo",
    "oasis", "robar", "ninos", "tejer", "recto", "azada", "madre", "negro", "grado", "verde",
    "sumar", "agrio", "resta", "lider", "voraz", "enojo", "vicio", "pesar", "pelea", "fruto",
    "epico", "cerdo", "burla", "falso", "cifra", "actor", "fijar", "burro", "dudar", "junto",
    "carro", "monte", "deuda", "huevo", "signo", "tapar", "tenue", "sutil", "mente", "cargo",
    "pisar", "rubro", "pista", "clima", "clara", "algun", "motin", "costa", "trama", "movil",
    "fauna", "linda", "trato", "notar", "marco", "axial", "zorro", "pulso", "noble", "obrar",
    "rigor", "obeso", "linea", "regir", "vital", "calle", "ruido", "serie", "iluso", "favor",
    "topar", "autor", "guiar", "veraz", "tirar", "ancho", "sagaz", "shock", "dosis", "drama",
    "ceder", "barco", "curso", "busca", "rogar", "guapo", "fuera", "danar", "elite", "prado",
    "marca", "garbo", "oeste", "virus", "matiz", "reves", "rodar", "catre", "extra", "elote",
    "cruel", "ritmo", "avaro", "docto", "staff", "idolo", "omiso", "chica", "curva", "jaula",
    "llama", "velar", "ojota", "bahia", "avido", "ebrio", "urdir", "baile", "nueva", "yacer",
    "tenia", "stand", "gesto", "citar", "valle", "ahito", "nicho", "silla", "ganas", "sitio",
    "cenir", "negar", "vigor", "vuelo", "docil", "bravo", "lista", "vista", "chapa", "cueva",
    "cesar", "firma", "fuego", "usado", "pacto", "letal", "flojo", "usual", "ameno", "lucir",
    "buena", "pilar", "necio", "habla", "hacia", "huida", "tumba", "duelo", "astro", "venir",
    "lapiz", "canon", "jalar", "avion", "magia", "unido", "banco", "pompa", "aquel", "agudo",
    "moral", "torpe", "furia", "hobby", "aviso", "apice", "tesis", "arduo", "digno", "rabia",
    "obito", "abuso", "norte", "rival", "ojear", "genio", "faena", "raudo", "ozono", "trozo",
    "valer", "ijada", "herir", "temer", "paseo", "tapia", "apego", "salon", "coche", "fallo",
    "vejez", "hielo", "socio", "rural", "resto", "sanar", "cerro", "carga", "techo", "parca",
    "horda", "mando", "ileso", "legar", "ligar", "rasgo", "yerro", "humor", "terco", "mojar",
    "tosco", "opaco", "sabor", "lobby", "cagar", "leche", "pleno", "heroe", "senil", "yermo",
    "cabal", "pared", "feroz", "alzar", "pavor", "poeta", "ojera", "gasto", "otear", "ansia",
    "venia", "canal", "soler", "mitad", "atrio", "bruto", "caida", "pauta", "beodo", "etnia",
    "bogar", "cutre", "metal", "lucro", "droga", "borde", "surco", "harto", "dogma", "susto",
    "pulir", "nieve", "menos", "raspa", "costo", "rezar", "falaz", "sudar", "parra", "ganso",
    "novio", "tedio", "presa", "toque", "lapso", "cajon", "salto", "koala", "fosil", "amado",
    "media", "santo", "relax", "lavar", "menor", "ninfa", "molde", "doble", "simil", "chino",
    "catar", "falla", "jerga", "alado", "navio", "rayar", "bruja", "ruina", "raton", "radio",
    "errar", "rozar", "barro", "letra", "super", "lycra", "diosa", "regio", "quedo", "verbo",
    "aunar", "tenso", "balon", "prisa", "obice", "rumor", "plazo", "zurdo", "Jesus", "carne",
    "rango", "poema", "secar", "besar", "odiar", "angel", "picar", "idear", "jiron", "reino",
    "ninez", "llave", "plato", "nuera", "tumor", "anexo", "basto", "fatal", "caber", "hilar",
    "ayuno", "atroz", "ideas", "truco", "rocio", "banda", "ardid", "boton", "turba", "circo",
    "envio", "plaza", "gruta", "vapor", "hueso", "hurto", "mutuo", "cisma", "junta", "enano",
    "semen", "bolso", "selva", "rampa", "atras", "rollo", "vagar", "botar", "salvo", "feria",
    "acero", "llano", "porte", "fugaz", "mitin", "robot", "calvo", "moler", "uvula", "rehen",
    "multa", "teñir", "timon", "fatuo", "callo", "torre", "impar", "otero", "flora", "untar",
    "cavar", "vedar", "ujier", "pugna", "gesta", "batir", "zafio", "tacto", "urgir", "nimio",
    "heces", "probo", "manso", "short", "telar", "mueca", "fibra", "vetar", "ronda", "traje",
    "vivaz", "casar", "peste", "coste", "aovar", "trino", "nadar", "abajo", "treta", "verso",
    "bolsa", "traba", "polvo", "coser", "bulto", "barra", "quiza", "disco", "pasta", "tañer",
    "arena", "plaga", "yelmo", "aereo", "bulla", "pudor", "reina", "hosco", "coito", "mimar",
    "novel", "votar", "monje", "atajo", "vacuo", "fecha", "hedor", "azote", "atado", "berma",
    "cuota", "espia", "curvo", "vejar", "oxear", "ruego", "orate", "haren", "malla", "mixto",
    "parir", "cirio", "choza", "kefir", "indio", "rubio", "barca", "manar", "brazo", "patio",
    "sesgo", "nariz", "mamar", "atril", "golfo", "grano", "ajado", "yerba", "exodo", "pasmo",
    "cruce", "gueto", "tribu", "ataud", "tutor", "cegar", "sobra", "impio", "trazo", "cazar",
    "prosa", "pillo", "valia", "crudo", "gemir", "rugir", "morro", "panel", "himno", "asear",
    "ardor", "bañar", "perla", "istmo", "cauce", "utero", "pinta", "barba", "helar", "okupa",
    "buque", "tenis", "dardo", "arder", "tabla", "brote", "censo", "lanza", "finca", "fruta",
    "trago", "bando", "torta", "rodeo", "quema", "pecho", "sopor", "araña", "tieso", "sudor",
    "vario", "civil", "yogur", "funda", "latir", "reñir", "cenit", "manta", "gnomo", "falda",
    "raido", "hebra", "ocupa", "recio", "musgo", "bruma", "minar", "oreja", "zanja", "preso",
    "apodo", "tasar", "timar", "macho", "gorra", "rapto", "coral", "asilo", "plata", "saldo",
    "savia", "casto", "canto", "nylon", "prole", "colar", "ambos", "brujo", "animo", "magro", 
    "temas", "hondo", "cariz", "cesta", "persa", "nimbo", "farsa", "falto", "bomba", "pañal",
    "peaje", "tropa", "bicho", "laico", "saeta", "grasa", "perra", "placa", "brezo", "clavo",
    "lerdo", "terso", "halar", "acoso", "abono", "aliar", "etico", "rotar", "anejo", "buril",
    "ducha", "efebo", "yerto", "jaleo", "cuero", "chulo", "tallo", "canoa", "monto", "porno",
    "yunta", "celda", "agape", "porra", "primo", "yegua", "acaso", "casco", "farol", "frito",
    "galan", "guisa", "fuero", "desde", "trapo", "labio", "mareo", "zafar", "trono", "judio",
    "ganga", "usura", "calar", "soplo", "naipe", "zaino", "penar", "cable", "aleta", "mecha",
    "emulo", "domar", "fiera", "aojar", "monja", "fardo", "junco", "viril", "axila", "cubil",
    "pollo", "llaga", "talud", "solaz", "pardo", "colmo", "limar", "oidor", "tibia", "cuate",
    "sorna", "ultra", "halla", "beato", "cursi", "quita", "sonda", "guion", "honra", "limbo",
    "brasa", "segar", "mudar", "gorro", "podar", "nandu", "justa", "orgia", "rubor", "plebe",
    "ornar", "egida", "talla", "bazar", "tapon", "titan", "esmog", "rizar", "labia", "cebar",
    "doler", "cerco", "renta", "caido", "dueto", "nevar", "hiato", "alero", "ixtle", "lloro",
    "kepis", "gramo", "ovalo", "talar", "apero", "vagon", "pizca", "jabon", "vulva", "marea",
    "pecar", "cabra", "blusa", "asado", "lamer", "dorso", "glosa", "bardo", "aforo", "aldea",
    "pesca", "lente", "flota", "jadeo", "apuro", "garra", "credo", "cobro", "cutis", "vulgo",
    "tinte", "crema", "gallo", "fisco", "arabe", "freno", "hipar", "natal", "hucha", "varon",
    "ungir", "joder", "beber", "video", "caqui", "palma", "secta",
    
];
const totalPalabras5letras = palabras5Letras.length;

const palabras6Letras = [
  "pensar", "ludico", "ademas", "soltar", "grande", "cambio", "fuerte", "equipo", "suelta", "muerte",
  "origen", "modelo", "accion", "imagen", "aunque", "quitar", "optimo", "zapato", "dinero", "alegre",
  "dormir", "medida", "hombre", "eterno", "camino", "cuidar", "formar", "crecer", "objeto", "blanco",
  "perder", "enviar", "factor", "pintar", "poseer", "metodo", "lograr", "servir", "cuenta", "tiempo",
  "fuerza", "porque", "imitar", "relato", "cuerpo", "volver", "vision", "llegar", "contar", "prueba",
  "sentir", "sector", "basico", "asunto", "saltar", "fuente", "efecto", "ayudar", "avance", "maleta",
  "centro", "opcion", "evocar", "humano", "arriba", "asumir", "propio", "oferta", "salida", "tratar",
  "rapido", "buscar", "suceso", "inutil", "fertil", "omitir", "oscuro", "enigma", "vender", "triste",
  "evitar", "carino", "aludir", "mandar", "afable", "ocupar", "emanar", "cubrir", "acoger", "comodo",
  "anadir", "mejora", "numero", "pueblo", "debido", "llevar", "alumno", "regalo", "calido", "hablar",
  "divino", "evento", "virtud", "doctor", "excusa", "manera", "activo", "social", "ambito", "hallar",
  "surgir", "estado", "desear", "elevar", "timido", "padres", "niebla", "cantar", "seguir", "unidad",
  "indole", "puente", "faltar", "agenda", "debate", "cierto", "educar", "querer", "solido", "pasion",
  "entrar", "idoneo", "hazana", "huella", "crisis", "pronto", "coraje", "astuto", "rostro", "bonito",
  "agente", "ocioso", "ciudad", "delito", "raspar", "motivo", "elogio", "vereda", "correr", "enorme",
  "cerrar", "engano", "anotar", "topico", "pasado", "limite", "apoyar", "oficio", "lluvia", "sumiso",
  "adorar", "limpio", "empeno", "eficaz", "elegir", "innato", "mentor", "placer", "reunir", "examen",
  "pleito", "pesado", "amable", "ubicar", "bailar", "desden", "tamano", "pasear", "ironia", "diseno",
  "fragil", "genero", "ligero", "comida", "sombra", "amplio", "mordaz", "osadia", "famoso", "ultimo",
  "azuzar", "aspero", "charla", "minimo", "vuelta", "captar", "cuando", "aislar", "axioma", "oculto",
  "acusar", "lanzar", "fraude", "inicio", "espeso", "mentir", "margen", "fresco", "actual", "anhelo",
  "nombre", "escaso", "severo", "amparo", "correo", "normal", "llenar", "nucleo", "nitido", "figura",
  "sufrir", "tierra", "eolico", "rutina", "patron", "cabeza", "gustar", "musica", "partir", "indice",
  "salvar", "marcar", "actuar", "asiduo", "verdad", "maximo", "animar", "sobrio", "llorar", "probar",
  "apelar", "tipico", "avisar", "jardin", "mision", "novato", "edicto", "luchar", "cuento", "frente",
  "gracia", "habito", "empero", "nocivo", "romper", "intimo", "rastro", "azucar", "pareja", "seguro",
  "gratis", "muerto", "atraer", "tirano", "codigo", "waffle", "fiesta", "puerta", "helado", "teoria",
  "acceso", "frijol", "dentro", "exigir", "acabar", "sonido", "pedazo", "apagar", "fervor", "urbano",
  "cortar", "quedar", "riesgo", "empleo", "piedad", "formal", "rodear", "tregua", "causal", "futuro",
  "juntar", "adorno", "carril", "amargo", "estilo", "situar", "narrar", "status", "quizas", "faceta",
  "gastar", "fusion", "gritar", "mojado", "juicio", "gigolo", "pereza", "precio", "grabar", "simple",
  "vencer", "trazar", "legado", "global", "misiva", "maldad", "fundar", "afecto", "estima", "herida",
  "ritual", "atacar", "titulo", "basura", "tacano", "labial", "puesto", "angulo", "atento", "locura",
  "emitir", "causar", "osculo", "yunque", "merito", "pseudo", "manejo", "colgar", "altivo", "acudir",
  "espejo", "crimen", "olvido", "medico", "linaje", "locuaz", "perdon", "quemar", "volcar", "gremio",
  "escala", "frenar", "suplir", "genial", "soldar", "enebro", "operar", "erigir", "terror", "obrero",
  "nocion", "hostil", "entero", "cumbre", "celoso", "hybris", "cursar", "bosque", "fulgor", "reposo",
  "burlar", "trampa", "guerra", "bisono", "viajar", "dureza", "barato", "agitar", "ataque", "ligado",
  "fundir", "cierre", "mezcla", "eximio", "sujeto", "proeza", "copiar", "inerte", "ibidem", "corona",
  "adagio", "llamar", "macizo", "suerte", "bondad", "impetu", "nacion", "hierro", "tocayo", "lujoso",
  "callar", "manual", "diente", "humedo", "perito", "eximir", "region", "clamar", "jovial", "etereo",
  "abismo", "suelto", "estres", "pelota", "gentil", "marron", "aciago", "cortes", "gelido", "zagua",
  "optica", "opinar", "pescar", "abolir", "prever", "rencor", "previo", "cargar", "dotado", "enlace",
  "carcel", "inepto", "azotar", "orilla", "manana", "tienda", "morder", "monton", "planta", "remoto",
  "parada", "grueso", "hastio", "horror", "quieto", "silbar", "alivio", "premio", "toxico", "bonita",
  "panico", "esposo", "bufalo", "clavar", "forjar", "vulgar", "afecta", "lejano", "valido", "chispa",
  "chocar", "lengua", "surcar", "physis", "oceano", "pillar", "cuarto", "danino", "hurtar", "tierno",
  "rigido", "editar", "espera", "halcon", "sosten", "batuta", "alabar", "altura", "dibujo", "viento",
  "frugal", "cuadro", "adulto", "esmero", "tender", "exacto", "juzgar", "anillo", "brillo", "evadir",
  "viable", "montar", "gitano", "aurora", "exiguo", "hierba", "jibaro", "kinder", "acorde", "agrado",
  "nativo", "exceso", "trepar", "apatia", "blando", "reparo", "sobrar", "colera", "acatar", "junior",
  "animal", "logica", "marcha", "cadena", "tacito", "churro", "diario", "dictar", "subito", "casual",
  "eludir", "demora", "idioma", "inocuo", "dilema", "sueter", "airoso", "esfera", "mirada", "infimo",
  "caduco", "receso", "zarpar", "espiar", "ladron", "piedra", "brotar", "hambre", "tutela", "contra",
  "cocina", "perfil", "organo", "utopia", "apilar", "lucido", "oponer", "brusco", "pecado", "menudo",
  "ubicuo", "brecha", "olfato", "egreso", "mental", "inicuo", "logico", "precoz", "cupula", "traste",
  "mueble", "candor", "galeno", "pelear", "apunte", "vecino", "bypass", "fluido", "temido", "fiable",
  "pirata", "macula", "alegar", "llanto", "ensayo", "baldio", "agenda", "fallar", "muchos", "flotar",
  "penoso", "variar", "flecha", "ansiar", "palpar", "ofensa", "griego", "lidiar", "fisico", "alerta",
  "fatiga", "gloton", "recelo", "verter", "aliado", "cruzar", "mortal", "puerto", "hundir", "esbozo",
  "encima", "yogurt", "sereno", "tocado", "kimono", "alojar", "aparte", "franco", "ninera", "gusano",
  "odioso", "grieta", "jarron", "pintor", "vergel", "rincon", "hereje", "jubilo", "baston", "trauma",
  "comite", "oyente", "idiota", "erguir", "cabana", "apenas", "ilegal", "nomada", "irreal", "subida",
  "parado", "maxima", "visita", "vestir", "choque", "beldad", "tesoro", "mesura", "maduro", "exento",
  "embate", "emisor", "apogeo", "cumulo", "primor", "colina", "dudoso", "palido", "gloria", "doblar",
  "ductil", "fingir", "sotana", "joroba", "dorado", "fragor", "celula", "heleno", "pagano", "rosado",
  "borrar", "avalar", "elegia", "versar", "pactar", "sangre", "pulsar", "diluir", "ignoto", "jocoso",
  "merced", "arroyo", "idilio", "fabula", "cuerda", "existe", "amante", "costar", "averia", "emular",
  "prenda", "aducir", "ladrar", "abuelo", "modulo", "madera", "bienes", "sonoro", "devoto", "zurrar",
  "taller", "visual", "pasivo", "traves", "criado", "cobrar", "ahorro", "veneno", "colega", "siervo",
  "cordon", "saqueo", "comico", "estafa", "intuir", "compra", "dadiva", "amoral", "umbrio", "goloso",
  "ahinco", "licito", "aseado", "ovillo", "agonia", "boceto", "latido", "soplar", "tejido", "hurano",
  "arcano", "odisea", "escena", "debajo", "overol", "calmar", "abrigo", "cartel", "masivo", "pureza",
  "zurcir", "vagina", "deceso", "medrar", "helice", "vileza", "teatro", "templo", "privar", "honrar",
  "arisco", "tragar", "abogar", "pedido", "manija", "jinete", "lexico", "espada", "obviar", "alejar",
  "germen", "guarda", "satira", "orbita", "enredo", "umbral", "violar", "alarma", "ciclon", "compas",
  "titere", "caudal", "detras", "enfado", "sexual", "metido", "pesimo", "moneda", "musico", "ganado",
  "turbar", "adular", "reacio", "sesion", "hombro", "torcer", "acervo", "retono", "mierda", "chofer",
  "adepto", "chorro", "retiro", "gemido", "lustre", "belico", "pulcro", "lozano", "chiste", "velada",
  "tenido", "ahogar", "rebaja", "timbre", "mermar", "saciar", "hostia", "kiosco", "avidez", "sigilo",
  "varios", "patria", "vuelto", "picaro", "lesion", "mediar", "livido", "verbal", "cyborg", "abonar",
  "agotar", "uchuva", "abadia", "acunar", "bestia", "nutrir", "ladino", "nevado", "boleto", "cuanto",
  "trance", "vaciar", "instar", "tienen", "ajuste", "huelga", "olimpo", "pueril", "chisme", "febril",
  "nacido", "fresca", "muneca", "islote", "pajaro", "manjar", "aserto", "anclar", "bebida", "turbio",
  "recaer", "loable", "abrazo", "neutro", "inopia", "pupilo", "pagina", "cigoto", "espina", "infame",
  "alcoba", "afanar", "brutal", "fiasco", "sabido", "parque", "maceta", "forzar", "mister", "tramar",
  "diablo", "tomate", "prensa", "pesada", "virgen", "asesor", "champu", "slogan", "filtro", "recibo",
  "abatir", "cayado", "adusto", "saludo", "manada", "natura", "temple", "poesia", "guante", "herido",
  "lesivo", "regazo", "pienso", "matriz", "ceniza", "jauria", "baladi", "camara", "vibrar", "medula",
  "enojar", "otrora", "acosar", "encono", "armado", "primar", "carnal", "mancha", "atavio", "sierra",
  "firmar", "guiñar", "asceta", "tetera", "resena", "sketch", "rotura", "culpar", "paramo", "cuesta",
  "crater", "rendir", "ropero", "concha", "cinico", "plagio", "atizar", "gracil", "violin", "ornato",
  "mustio", "frotar", "pastel", "restar", "gandul", "decoro", "cesion", "deudor", "jarabe", "obtuso",
  "hijole", "cabala", "mohoso", "arguir", "tardio", "labrar", "cuello", "finura", "formas", "psique",
  "lumbre", "tornar", "surtir", "marido", "zurron", "barrio", "divisa", "fetido", "laguna", "sentar",
  "vasija", "fiscal", "acerbo", "asolar", "escudo", "kermes", "moreno", "fulano", "exilio", "airado",
  "cuatro", "bocado", "inerme", "moroso", "canoro", "recado", "hocico", "abusar", "atinar", "celibe",
  "fausto", "nervio", "climax", "balcon", "gestor", "jugada", "expiar", "dispar", "rumiar", "sueldo",
  "tropel", "enjuto", "recato", "asalto", "charco", "peaton", "rareza", "sellar", "avivar", "gnosis",
  "meseta", "pulido", "patada", "antano", "calzar", "mitico", "esposa", "ulcera", "cansar"
  

  ];
  const totalPalabras6letras = palabras6Letras.length;



  const palabras7Letras = [
    "conocer", "proceso", "hermosa", "mejorar", "interes", "aspecto", "momento", "tambien", "mostrar", "valores",
    "funcion", "durante", "cumplir", "ofrecer", "recibir", "impacto", "calidad", "onirico", "motivar", "sistema",
    "atender", "aplicar", "estudio", "emocion", "control", "gracias", "extrano", "ilusion", "caminar", "influir",
    "golpear", "intenso", "sublime", "guardar", "resumen", "mensaje", "otorgar", "generar", "empezar", "montana",
    "inferir", "cliente", "obligar", "senalar", "afirmar", "asistir", "detalle", "existir", "plasmar", "muestra",
    "delgado", "definir", "armonia", "exponer", "termino", "obtener", "iconico", "dificil", "honesto", "urgente",
    "indicar", "ejercer", "entidad", "negocio", "desafio", "primero", "incluir", "castigo", "posible", "aquello",
    "enfermo", "escasez", "avanzar", "trabajo", "esencia", "enfoque", "ensenar", "curioso", "revelar", "sentido",
    "inmenso", "energia", "ordenar", "asombro", "opinion", "escuela", "columna", "jornada", "entrada", "detener",
    "dirigir", "parecer", "visitar", "sincero", "imponer", "racismo", "reclamo", "pequeno", "redimir", "ampliar",
    "perdido", "aceptar", "limitar", "arrojar", "incitar", "confiar", "derrota", "secarse", "esperar", "aportar",
    "extraer", "memoria", "tecnica", "aptitud", "campana", "habitar", "ventaja", "separar", "maestro", "afectar",
    "despues", "colocar", "enfocar", "antiguo", "adicion", "extremo", "estatus", "abordar", "ajustar", "reunion",
    "elevado", "publico", "celebre", "comprar", "derecho", "brindar", "cambiar", "natural", "alterar", "ruidoso",
    "exhibir", "revisar", "actitud", "costoso", "alegria", "mentira", "soporte", "aspirar", "hermoso", "postura",
    "carecer", "perenne", "radical", "evaluar", "referir", "agarrar", "venerar", "abarcar", "sendero", "malvado",
    "reducir", "crucial", "planear", "escrito", "esteril", "riqueza", "anhelar", "moderno", "victima", "inducir",
    "diverso", "firmeza", "cerrado", "refutar", "sugerir", "valorar", "dividir", "vinculo", "acceder", "fracaso",
    "excluir", "espacio", "invadir", "potente", "invocar", "suponer", "dominar", "persona", "critico", "valioso",
    "ingerir", "relatar", "emplear", "cosecha", "ocupado", "enganar", "pobreza", "voluble", "dedicar", "ilustre",
    "egoista", "alianza", "certeza", "equidad", "regalar", "vigilar", "empresa", "repetir", "entrega", "alcance",
    "mezclar", "simbolo", "artista", "lugubre", "regular", "siempre", "tributo", "directo", "materia", "decidir",
    "analogo", "soledad", "ignorar", "habitat", "archivo", "consejo", "peligro", "promesa", "respeto", "expirar",
    "dilatar", "cavilar", "ejemplo", "aumento", "tampoco", "reflejo", "belleza", "salvaje", "validar", "aclarar",
    "euforia", "residir", "aliento", "letargo", "agravio", "adoptar", "novedad", "apetito", "inmerso", "intento",
    "rechazo", "exotico", "palabra", "cansado", "dominio", "atonito", "demente", "sucinto", "general", "admirar",
    "circulo", "formado", "gestion", "erudito", "regimen", "invento", "amenaza", "constar", "padecer", "cercano",
    "similar", "periodo", "apuntar", "recoger", "centrar", "solemne", "acuerdo", "ahorrar", "aflojar", "someter",
    "cultura", "vuestra", "confort", "abierto", "sonrisa", "deducir", "familia", "supremo", "recurso", "amoroso",
    "monarca", "superar", "creador", "innovar", "entorno", "reforma", "copioso", "olvidar", "integro", "intacto",
    "iniciar", "retirar", "cautivo", "preciso", "furioso", "manejar", "perfume", "iceberg", "callado", "aprecio",
    "suceder", "marcado", "consumo", "titular", "anciano", "admitir", "mundano", "excitar", "autobus", "aburrir", 
    "liberar", "alusion", "renegar", "volumen", "debatir", "ocultar", "ingenuo", "activar", "festejo", "impedir",
    "docente", "deleite", "merecer", "agradar", "candido", "molesto", "sombrio", "miedoso", "volatil", "planeta",
    "deficit", "liderar", "cuidado", "meditar", "adaptar", "demanda", "insulto", "virtual", "estimar", "autoria",
    "dulzura", "sabroso", "dormido", "destino", "mayoria", "incluso", "intriga", "asustar", "proveer", "modesto",
    "ofuscar", "inicial", "ofender", "incapaz", "brasier", "indagar", "escalar", "defensa", "replica", "presion",
    "acertar", "ausente", "formato", "enojado", "amistad", "humilde", "version", "cobarde", "empatia", "hermano",
    "vigente", "diferir", "sagrado", "retener", "barbaro", "alentar", "latente", "cabello", "traidor", "prolijo",
    "pionero", "confuso", "imperio", "piadoso", "agregar", "secreto", "critica", "impulso", "mitigar", "diseñar",
    "egregio", "cirugia", "juguete", "emerger", "perdido", "anuncio", "otredad", "hoguera", "lealtad", "colosal",
    "anonimo", "ruptura", "ocasion", "ficcion", "ocurrir", "conciso", "escoger", "derivar", "sancion", "delatar",
    "dibujar", "estable", "incauto", "sensual", "extenso", "rebelde", "ansioso", "agujero", "sujetar", "arribar",
    "proximo", "efimero", "mercado", "catedra", "moderar", "paridad", "funeral", "alargar", "aficion", "cronico",
    "exaltar", "condena", "perdida", "furtivo", "incidir", "omision", "corazon", "iglesia", "efusivo", "cocinar",
    "sensato", "notable", "limpiar", "tortura", "ensayar", "ingreso", "abdicar", "asociar", "patente", "flagelo",
    "abrazar", "trivial", "vacante", "realzar", "nupcias", "difamar", "tsunami", "enfasis", "educado", "robusto",
    "grosero", "cordial", "delirio", "partida", "tactica", "rapidez", "lateral", "eslogan", "clasico", "orgullo",
    "nombrar", "cultivo", "empapar", "acercar", "envidia", "ilicito", "razonar", "miembro", "invitar", "apartar",
    "vomitar", "versado", "vanidad", "remitir", "defecto", "prestar", "informe", "triunfo", "abrupto", "sosiego",
    "embuste", "despojo", "nodriza", "asignar", "garante", "benigno", "maldito", "unisono", "bandada", "estrago",
    "nublado", "injusto", "lacerar", "lectura", "terapia", "quimera", "gigante", "absurdo", "malicia", "terreno",
    "incesto", "mistico", "aprobar", "talento", "excelso", "infeliz", "figurar", "derogar", "adornar", "interno",
    "reserva", "delirar", "sumario", "codicia", "infante", "ventana", "decorar", "esquema", "ambiguo", "dialogo",
    "especie", "agitado", "retomar", "frivolo", "prodigo", "colegio", "oracion", "agrupar", "escapar", "afilado",
    "refugio", "agravar", "esquivo", "adecuar", "reparar", "paisaje", "relieve", "oxigeno", "moldear", "colibri",
    "visible", "risueño", "encanto", "ironico", "salario", "genuino", "empujar", "opuesto", "simular", "falacia",
    "alinear", "revivir", "abogado", "caricia", "denotar", "nitidez", "llamada", "leccion", "bandera", "milagro", 
    "seccion", "escolar", "expedir", "cascara", "experto", "disipar", "astucia", "cordura", "sinuoso", "porcion",
    "variado", "tecnico", "pedante", "maqueta", "desazon", "devorar", "maquina", "enemigo", "usuario", "ganador",
    "ciencia", "caballo", "filtrar", "navegar", "noticia", "celeste", "apagado", "injuria", "acechar", "corroer",
    "aditivo", "mandato", "heraldo", "heroico", "popular", "diafano", "errante", "segundo", "longevo", "egoismo",
    "gastado", "credito", "militar", "agotado", "augurar", "nefasto", "absorto", "combate", "caridad", "capital",
    "disputa", "aparato", "usurpar", "oneroso", "basarse", "tragico", "insigne", "cautela", "estatua", "encajar",
    "cronica", "lujuria", "atrapar", "tension", "zozobra", "resumir", "inusual", "soltura", "turismo", "epilogo",
    "radicar", "indicio", "cristal", "fortuna", "repleto", "erroneo", "honrado", "situado", "ternura", "regreso",
    "pintura", "sintoma", "secuela", "deporte", "premisa", "tolerar", "utopico", "barrera", "retrato", "tiritar",
    "mutismo", "bonanza", "menguar", "viajero", "amuleto", "mudanza", "diestro", "reposar", "arreglo", "calculo",
    "comarca", "seducir", "externo", "abyecto", "objetar", "divisar", "esfinge", "permiso", "vocablo", "vertigo",
    "oblicuo", "asiento", "desviar", "ultraje", "carrera", "profuso", "metrica", "retraso", "sonreir", "resulta",
    "lamento", "exitoso", "rigidez", "llegada", "acabado", "alusivo", "central", "spoiler", "trafico", "arropar",
    "adverso", "acordar", "fecundo", "disfraz", "mochila", "asesino", "relegar", "semilla", "regañar", "marchar",
    "ensueño", "parcial", "cotejar", "pericia", "genesis", "acicate", "cavidad", "puntual", "arcaico", "batalla",
    "heredar", "delicia", "loteria", "sacudir", "oriundo", "bellaco", "querido", "vestido", "sembrar", "oquedad",
    "vastago", "apretar", "oscilar", "frenesi", "estupor", "auxilio", "ofrenda", "calmado", "hechizo", "sobajar",
    "notorio", "anormal", "soborno", "decreto", "cerebro", "llanura", "fabrica", "brillar", "renovar", "funesto",
    "austero", "marasmo", "extasis", "tetrico", "formula", "alertar", "oraculo", "cancion", "elogiar", "enlazar",
    "mascara", "apenado", "adherir", "ingenio", "amainar", "paquete", "renacer", "emblema", "redondo", "miseria",
    "asentar", "agredir", "litigio", "patraña", "ventura", "brincar", "ascenso", "ajedrez", "liviano", "emision",
    "oficina", "estigma", "abrigar", "privado", "creible", "impeler", "aliviar", "atenuar", "recrear", "rustico",
    "higiene", "vacilar", "testigo", "seguido", "relajar", "prender", "tratado", "selecto", "remover", "charlar",
    "afrenta", "pomposo", "angosto", "vetusto", "oxidado", "evasion", "leyenda", "apatico", "poblado", "esbozar",
    "certero", "soltero", "declive", "paraiso", "eslabon", "clerigo", "panacea", "humedad", "mediano", "eclipse",
    "quebrar", "zepelin", "mencion", "huracan", "ubicado", "botella", "mendigo", "soleado", "liberal", "recinto",
    "timidez", "ajetreo", "temblar", "funebre", "volador", "validez", "esclavo", "evacuar", "cotizar", "turista",
    "surtido", "bizarro", "colecta", "abanico", "esbelto", "inmovil", "galante", "denuedo", "repudio", "establo",
    "deseado", "laborar", "embargo", "abatido", "coartar", "aplazar", "moverse", "mascota", "delegar", "silueta",
    "prologo", "agudeza", "gradual", "devenir", "relevar", "trueque", "ilogico", "inedito", "varilla", "oprobio",
    "bombero", "ahondar", "festivo", "excavar", "emotivo", "animado", "exhalar", "zumbido", "amarrar", "arrasar",
    "almacen", "factura", "desecho", "abdomen", "cadaver", "impasse", "pasmado", "acogida", "inhalar", "arbitro",
    "pizarra", "despota", "estirar", "gravoso", "grafico", "limpido", "soldado", "inmoral", "cascada", "inercia",
    "remanso", "revocar", "estadio", "listado", "cortejo", "aferrar", "plantar", "fluidez", "alinado", "aclamar",
    "irritar", "biberon", "apuesta", "residuo", "cuspide", "torcido", "imperar", "brujula", "placido", "fomento",
    "teorico", "inundar", "erosion", "premiar", "oprimir", "balance", "modelar", "madurez", "temible", "collage",
    "escucha", "fachada", "halagar", "necedad", "modorra", "vasallo", "alegrar", "calzado", "afligir", "neutral",
    "regalia", "estampa", "relleno", "textura", "exceder", "tremulo", "atisbar", "oriente", "parrafo", "cintura",
    "encargo", "audacia", "enviado", "profano", "madurar", "ninguno", "atentar", "melodia", "horario", "credulo",
    "bohemio", "quietud", "vencido", "indexar", "candado", "descaro", "hibrido", "digerir"
  ];
  const totalPalabras7letras = palabras7Letras.length;


  // console.log("Total 4 letras: "+totalPalabras4letras);
  // console.log("Total 5 letras: "+totalPalabras5letras);
  // console.log("Total 6 letras: "+totalPalabras6letras);
  // console.log("Total 7 letras: "+totalPalabras7letras);




  

